# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2.1'
name: pgpool
services:
    web:
        image: ${DOCKER_REGISTRY-}web
        container_name: codemaze_web
        build:
            context: .
            dockerfile: Web/Dockerfile
        ports:
            - 5000:80
            - 5001:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
            - redis-cache
    db:
        image: postgres:latest
        restart: always
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        # or set shared memory limit when deploy via swarm stack
        #volumes:
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb
        environment:
          POSTGRES_DB: c06db
          POSTGRES_USER: c06dbo
          POSTGRES_PASSWORD: admin2024
        ports:
          - 5432:5432
        volumes:
          - db_data:/var/lib/postgresql/data
    # pg-0:
    #     image: docker.io/bitnami/postgresql-repmgr:16.3.0
    #     ports:
    #       - 5432
    #     volumes:
    #       - pg_0_data:/bitnami/postgresql
    #     environment:
    #       - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
    #       - POSTGRESQL_USERNAME=c06dbo
    #       - POSTGRESQL_PASSWORD=admin2024
    #       - POSTGRESQL_DATABASE=c06db
    #       - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    #       - REPMGR_PRIMARY_HOST=pg-0
    #       - REPMGR_PARTNER_NODES=pg-1,pg-0
    #       - REPMGR_NODE_NAME=pg-0
    #       - REPMGR_NODE_NETWORK_NAME=pg-0
    #       - REPMGR_USERNAME=repmgr
    #       - REPMGR_PASSWORD=repmgrpassword
    # pg-1:
    #     image: docker.io/bitnami/postgresql-repmgr:16.3.0
    #     ports:
    #         - 5432
    #     volumes:
    #         - pg_1_data:/bitnami/postgresql
    #     environment:
    #         - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
    #         - POSTGRESQL_USERNAME=c06dbo
    #         - POSTGRESQL_PASSWORD=admin2024
    #         - POSTGRESQL_DATABASE=c06db
    #         - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    #         - REPMGR_PRIMARY_HOST=pg-0
    #         - REPMGR_PARTNER_NODES=pg-0,pg-1
    #         - REPMGR_NODE_NAME=pg-1
    #         - REPMGR_NODE_NETWORK_NAME=pg-1
    #         - REPMGR_USERNAME=repmgr
    #         - REPMGR_PASSWORD=repmgrpassword
    # pgpool:
    #     image: docker.io/bitnami/pgpool:4.5.2
    #     ports:
    #         - 5432:5432
    #     restart: always
    #     environment:
    #         - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
    #         - PGPOOL_SR_CHECK_USER=repmgr
    #         - PGPOOL_SR_CHECK_PASSWORD=repmgrpassword
    #         - PGPOOL_ENABLE_LDAP=no
    #         - PGPOOL_POSTGRES_USERNAME=postgres
    #         - PGPOOL_POSTGRES_PASSWORD=adminpassword
    #         - PGPOOL_ADMIN_USERNAME=admin
    #         - PGPOOL_ADMIN_PASSWORD=adminpassword
    #         - PGPOOL_ENABLE_LOAD_BALANCING=yes
    #         - PGPOOL_POSTGRES_CUSTOM_USERS=c06dbo
    #         - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=admin2024
    #     healthcheck:
    #         test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    redis-cache:
        image: docker.io/bitnami/redis:7.2
        ports:
            - 6379:6370
        restart: always
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - redis_data:/bitnami/redis/data

volumes:
  db_data:
   driver: local
  # pg_0_data:
  #   driver: local
  # pg_1_data:
  #   driver: local
  redis_data:
    driver: local  